apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: faas-netesd
  namespace: operation-dev-infra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: faas-netesd
    spec:
      containers:
      - name: faas-netesd
        image: functions/faas-netesd:0.5.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 150Mi
          limits:
            memory: 150Mi   # Adjust to suit needs
        env:
        - name: function_namespace
          value: operation-dev-infra
        - name: read_timeout
          value: "20s"
        - name: write_timeout
          value: "20s"
        - name: image_pull_policy
          value: "Always"
---
apiVersion: v1
kind: Service
metadata:
  name: faas-netesd
  namespace: operation-dev-infra
  labels:
    app: faas-netesd
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: faas-netesd