apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: faas-gateway
  namespace: operation-dev-infra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: faas-gateway
    spec:
      containers:
      - name: faas-gateway
        image: functions/gateway:0.8.0
        imagePullPolicy: Always
        env:
        - name: functions_provider_url
          value: "http://faas-netesd.operation-dev-infra.svc.cluster.local.:8080/" # Final `.` specifies an absolute address
#        - name: faas_nats_address
#          value: "nats.operation-dev-infra.svc.cluster.local."
#        - name: faas_nats_port
#          value: "4222"
        - name: direct_functions
          value: "true"                             # Functions are invoked directly over the overlay network
        - name: direct_functions_suffix
          value: "operation-dev-infra.svc.cluster.local."   # contains K8s namespace
        - name: read_timeout
          value: "35s"
        - name: write_timeout
          value: "35s"
        - name: upstream_timeout  # Must be smaller than read/write_timeout
          value: "30s"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 250Mi
          limits:
            memory: 250Mi   # Adjust to suit needs of deployment

---
apiVersion: v1
kind: Service
metadata:
  name: faas-gateway
  namespace: operation-dev-infra
  labels:
    app: faas-gateway
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: faas-gateway